import { readFile, writeFile, mkdir } from "node:fs/promises";
import {
  descriptions,
  integrations,
  pending,
  alternatives,
  features,
  quotes,
  cofounderTrail,
} from "./curation.mjs";
const read = async (name) =>
  JSON.parse(await readFile(`.audit/${name}.json`, "utf8"));
const [pulls, issues, commits, manifest, ancestry] = await Promise.all(
  ["pulls", "issues", "all-commits", "manifest", "ancestry"].map(read),
);
const own = (x) => ["MohamadKanso", "MoKanso"].includes(x);
const prUrl = (n) => `https://github.com/NousResearch/hermes-agent/pull/${n}`;
const ours = pulls.filter((x) => own(x.pr.user.login));
const integrationData = integrations.map((item) => {
  const target = pulls.find((x) => x.pr.number === item.via);
  if (!target?.pr.merged_at) throw new Error(`not merged: ${item.via}`);
  const credited = commits.filter(
    (c) =>
      (c.landedAuthor || c.landedCoauthor) &&
      c.linked.some((p) => p.number === item.via),
  );
  if (!credited.length) throw new Error(`no upstream credit for ${item.via}`);
  return {
    ...item,
    date: target.pr.merged_at,
    url: target.pr.html_url,
    by: target.pr.user.login,
    commits: credited.map((c) => c.commit.sha),
  };
});
const records = ours.map(
  ({ pr, files, comments, reviews, reviewComments, commits: prCommits }) => {
    const desc = descriptions[pr.number];
    if (!desc) throw new Error(`missing description ${pr.number}`);
    const landed = integrationData.find((x) => x.original === pr.number);
    const next = pending[pr.number];
    const status = landed
      ? "landed"
      : next
        ? "in review"
        : pr.state === "open"
          ? "open"
          : "closed";
    const related = new Set(
      [...`${pr.title}\n${pr.body}`.matchAll(/#(\d+)/g)].map((x) => +x[1]),
    );
    const titleIssue = pr.title.match(/\(#(\d+)\)/);
    if (titleIssue) related.add(+titleIssue[1]);
    const first =
      files.find(
        (f) => f.patch && !/(test|website|\.md$|contributors)/.test(f.filename),
      ) || files.find((f) => f.patch);
    return {
      number: pr.number,
      title: desc[0],
      githubTitle: pr.title,
      area: desc[1],
      summary: desc[2],
      url: pr.html_url,
      created: pr.created_at,
      updated: pr.updated_at,
      state: pr.state,
      status,
      mergedAt: pr.merged_at,
      head: pr.head.sha,
      additions: pr.additions,
      deletions: pr.deletions,
      landed: landed || null,
      pending: next
        ? {
            number: next,
            url: prUrl(next),
            state: pulls.find((x) => x.pr.number === next)?.pr.state || "open",
          }
        : null,
      alternative: alternatives[pr.number]
        ? prUrl(alternatives[pr.number])
        : null,
      issues: [...related].filter((n) =>
        issues.some((x) => x.issue.number === n && !x.issue.pull_request),
      ),
      files: files.map((f) => ({
        path: f.filename,
        additions: f.additions,
        deletions: f.deletions,
      })),
      commits: prCommits.map((c) => c.sha),
      feedback: [...comments, ...reviews, ...reviewComments]
        .filter((c) => !own(c.user.login))
        .map((c) => ({
          by: c.user.login,
          date: c.created_at || c.submitted_at,
          url: c.html_url,
          kind: c.state ? "review" : c.path ? "inline comment" : "comment",
          automated:
            /generated by AI|AI code review|Reviewed using Hermes-Agent/i.test(
              c.body || "",
            ),
        })),
      snippet: first
        ? {
            path: first.filename,
            text: first.patch.split("\n").slice(0, 28).join("\n"),
            url: `${pr.html_url}/files`,
          }
        : null,
    };
  },
);
const commitRecords = commits
  .map((c) => ({
    sha: c.commit.sha,
    title: c.commit.commit.message.split("\n")[0],
    date: c.commit.commit.author.date,
    url: c.commit.html_url,
    by: c.commit.author?.login || c.commit.commit.author.name,
    role: c.landedAuthor
      ? "author on main"
      : c.landedCoauthor
        ? "co-author on main"
        : own(c.commit.author?.login)
          ? "pr author"
          : "upstream commit in pr",
    onMain: c.landedAuthor || c.landedCoauthor,
    prs: c.authoredPRs,
    mergedThrough: c.linked.filter((p) => p.merged_at).map((p) => p.number),
    files: c.commit.files.map((f) => ({
      path: f.filename,
      additions: f.additions,
      deletions: f.deletions,
    })),
    stats: c.commit.stats,
  }))
  .sort((a, b) => b.date.localeCompare(a.date));
let mentions = [];
const addMention = (by, body, url, date, n, kind) => {
  if (!own(by) && /@(?:MohamadKanso|MoKanso)\b/i.test(body || ""))
    mentions.push({ by, url, date, number: n, kind });
};
for (const x of pulls) {
  addMention(
    x.pr.user.login,
    x.pr.body,
    x.pr.html_url,
    x.pr.created_at,
    x.pr.number,
    "pr description",
  );
  for (const c of [...x.comments, ...x.reviews, ...x.reviewComments])
    addMention(
      c.user.login,
      c.body,
      c.html_url,
      c.created_at || c.submitted_at,
      x.pr.number,
      "comment",
    );
}
for (const x of issues) {
  addMention(
    x.issue.user.login,
    x.issue.body,
    x.issue.html_url,
    x.issue.created_at,
    x.issue.number,
    "issue",
  );
  for (const c of x.comments)
    addMention(
      c.user.login,
      c.body,
      c.html_url,
      c.created_at,
      x.issue.number,
      "issue comment",
    );
}
mentions = [...new Map(mentions.map((m) => [m.url, m])).values()]
  .map((m) => ({
    ...m,
    title:
      pulls.find((x) => x.pr.number === m.number)?.pr.title ||
      issues.find((x) => x.issue.number === m.number)?.issue.title,
    credit: integrationData.some(
      (x) => x.via === m.number || x.original === m.number,
    )
      ? "landed contribution context"
      : "discussion or attribution context",
  }))
  .sort((a, b) => b.date.localeCompare(a.date));
const quoteData = quotes.map((q) => {
  const source = pulls.find((x) => x.pr.number === q.pr);
  const text = q.comment
    ? source.comments.find((c) => c.id === q.comment)?.body
    : source.pr.body;
  if (!text?.includes(q.quote)) throw new Error(`quote mismatch ${q.pr}`);
  if (q.quote.split(/\s+/).length > 25) throw new Error("quote too long");
  return {
    ...q,
    url: prUrl(q.pr) + (q.comment ? `#issuecomment-${q.comment}` : ""),
  };
});
const cofounderTrailData = cofounderTrail.map((item) => {
  const source = pulls.find((x) => x.pr.number === item.via);
  const integration = integrationData.find(
    (x) => x.original === item.original && x.via === item.via,
  );
  if (!source || source.pr.user.login !== "teknium1")
    throw new Error(`co-founder source is not by teknium1: ${item.via}`);
  if (!integration)
    throw new Error(`missing trail integration ${item.original}`);
  if (!source.pr.body?.includes(item.quote))
    throw new Error(`trail quote mismatch ${item.via}`);
  if (item.quote.split(/\s+/).length > 25)
    throw new Error(`trail quote too long ${item.via}`);
  return {
    ...item,
    sourceUrl: source.pr.html_url,
    originalUrl: prUrl(item.original),
    mergedUrl: source.pr.html_url,
    commitUrls: integration.commits.map(
      (sha) => commits.find((c) => c.commit.sha === sha)?.commit.html_url,
    ),
    kind: integration.kind,
  };
});
const featureData = features.map((f) => {
  const c = commits.find((x) => x.commit.sha === f.sha);
  const file = c?.commit.files.find((x) => x.filename === f.file);
  if (!file?.patch) throw new Error(`missing snippet ${f.id}`);
  return {
    ...f,
    snippet: {
      path: f.file,
      text: file.patch.split("\n").slice(0, 34).join("\n"),
      url: c.commit.html_url,
    },
    integration: integrationData.find((x) => x.original === f.id),
  };
});
const publicIssues = issues
  .filter((x) => !x.issue.pull_request)
  .map((x) => ({
    number: x.issue.number,
    title: x.issue.title,
    state: x.issue.state,
    url: x.issue.html_url,
    created: x.issue.created_at,
    author: x.issue.user.login,
    labels: x.issue.labels.map((l) => l.name),
    prs: records
      .filter((r) => r.issues.includes(x.issue.number))
      .map((r) => r.number),
  }))
  .sort((a, b) => b.number - a.number);
const data = {
  version: 1,
  checkedAt: manifest.checkedAt,
  main: ancestry.currentMain,
  repo: "NousResearch/hermes-agent",
  profile: "MohamadKanso",
  metrics: {
    prs: records.length,
    openPRs: records.filter((p) => p.state === "open").length,
    closedPRs: records.filter((p) => p.state === "closed").length,
    directMerges: records.filter((p) => p.mergedAt).length,
    landed: integrationData.length,
    authoredMain: commitRecords.filter((c) => c.role === "author on main")
      .length,
    coauthoredMain: commitRecords.filter((c) => c.role === "co-author on main")
      .length,
    prCommits: commitRecords.filter((c) => c.prs.length).length,
    authoredPrCommits: commitRecords.filter((c) => c.prs.length && own(c.by))
      .length,
    inspectedCommits: commitRecords.length,
    issues: publicIssues.length,
    authoredIssues: publicIssues.filter((i) => own(i.author)).length,
    mentions: mentions.length,
    tekniumMentions: mentions.filter((m) => m.by === "teknium1").length,
    scannedPRs: pulls.length,
    feedback: records.reduce((sum, r) => sum + r.feedback.length, 0),
  },
  integrations: integrationData,
  features: featureData,
  quotes: quoteData,
  cofounderTrail: cofounderTrailData,
  prs: records,
  commits: commitRecords,
  issues: publicIssues,
  mentions,
};
await mkdir("public/data", { recursive: true });
await writeFile("public/data/contributions.json", JSON.stringify(data));
console.log(data.metrics);
